"""add subscription fields

Revision ID: 26214c78b594
Revises: 2574bf66c7f1
Create Date: 2023-09-23 23:50:42.273241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26214c78b594'
down_revision = '2574bf66c7f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sub_is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('sub_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('stripe_sub_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_sub_id')
    op.drop_column('users', 'sub_until')
    op.drop_column('users', 'sub_is_active')
    # ### end Alembic commands ###