"""change_feedbacks_field

Revision ID: 3cc5193a694d
Revises: 62e72f9414f3
Create Date: 2024-01-28 13:10:59.276430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc5193a694d'
down_revision = '62e72f9414f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('feedbacks', sa.Column('user_email', sa.String()))
    op.execute('UPDATE feedbacks SET user_email = users.email FROM users WHERE feedbacks.user_id = users.id')
    op.create_foreign_key('feedbacks_user_email_fkey', 'feedbacks', 'users', ['user_email'], ['email'])

    op.drop_constraint('feedbacks_user_id_fkey', 'feedbacks', type_ ='foreignkey')
    op.drop_column('feedbacks', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('user_id', sa.UUID()))
    op.execute('UPDATE feedbacks SET user_id = users.id FROM users WHERE feedbacks.user_email = users.email')
    op.create_foreign_key('feedbacks_user_id_fkey', 'feedbacks', 'users', ['user_id'], ['id'])

    op.drop_constraint('feedbacks_user_email_fkey', 'feedbacks', type_ ='foreignkey')
    op.drop_column('feedbacks', 'user_email')
    # ### end Alembic commands ###
