"""add_airtable_field

Revision ID: 470f0e3d775d
Revises: d5a73f640d17
Create Date: 2024-02-23 13:29:03.739388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470f0e3d775d'
down_revision = 'd5a73f640d17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE languages SET lang_name='English (US)' WHERE lang_name='American English'")
    op.execute("UPDATE languages SET lang_name='English (UK)' WHERE lang_name='British English'")
    op.execute("UPDATE languages SET lang_name='Portuguese (Brazil)' WHERE lang_name='Brazilian Portuguese'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE languages SET lang_name='American English' WHERE lang_name='English (US)'")
    op.execute("UPDATE languages SET lang_name='British English' WHERE lang_name='English (UK)'")
    op.execute("UPDATE languages SET lang_name='Brazilian Portuguese' WHERE lang_name='Portuguese (Brazil)'")
    # ### end Alembic commands ###

