"""name[D

Revision ID: 4c1dae2170fc
Revises: 62e72f9414f3
Create Date: 2024-01-28 18:14:23.117407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

from core.status import StatEventTypeEnum

# revision identifiers, used by Alembic.
revision = '4c1dae2170fc'
down_revision = '3cc5193a694d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistic_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sqlalchemy_utils.types.choice.ChoiceType(StatEventTypeEnum, impl=sa.String()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.alter_column('feedbacks', 'id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedbacks', 'id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('statistic_events')
    # ### end Alembic commands ###
