"""botaccount

Revision ID: 58ce050de353
Revises: bf1c8126abb5
Create Date: 2023-12-26 18:40:47.780315

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '58ce050de353'
down_revision = 'bf1c8126abb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"""INSERT INTO users(id, email, hashed_password, used_sso, status, name, is_verified, balance, created, updated, total_created_prj, total_created_loc, total_secs_processed, total_paid) VALUES 
        (gen_random_uuid(), 'tgbot@vps.com', '$2b$12$eo6g28rEJXTrogVbY6VEHuMgFibBxtolugM8jyNthleBXEk2Axa6e', FALSE, 1, 'TGBot', TRUE, 2147483647, '{datetime.utcnow()}', '{datetime.utcnow()}', 0, 0, 0, 0)"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE email='tgbot@vps.com'")
    # ### end Alembic commands ###
