"""name

Revision ID: 62e72f9414f3
Revises: 58ce050de353
Create Date: 2024-01-27 18:17:42.764705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e72f9414f3'
down_revision = '58ce050de353'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('source', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('languages', sa.Column('target', sa.Boolean(), nullable=False, server_default='false'))
    op.execute("UPDATE languages SET source=true WHERE api_name IN ('en', 'ru', 'fr', 'de', 'it')")
    op.execute("UPDATE languages SET target=true WHERE api_name IN ('ru', 'fr', 'de', 'it')")
    op.execute("""INSERT INTO languages(id, lang_name, api_name, source, target) VALUES
        (gen_random_uuid(), 'Spanish', 'es', true, true),
        (gen_random_uuid(), 'British English', 'en-gb', false, true),
        (gen_random_uuid(), 'American English', 'en-us', false, true),
        (gen_random_uuid(), 'Portuguese', 'pt', true, true),
        (gen_random_uuid(), 'Brazilian Portuguese', 'pt-br', false, true),
        (gen_random_uuid(), 'Dutch', 'nl', true, true),
        (gen_random_uuid(), 'Ukrainian', 'uk', true, true),
        (gen_random_uuid(), 'Korean', 'ko', true, true),
        (gen_random_uuid(), 'Polish', 'pl', true, true),
        (gen_random_uuid(), 'Czech', 'cs', true, true),
        (gen_random_uuid(), 'Bulgarian', 'bg', true, true),
        (gen_random_uuid(), 'Swedish', 'sv', true, true),
        (gen_random_uuid(), 'Danish', 'da', true, true),
        (gen_random_uuid(), 'Finnish', 'fi', true, true),
        (gen_random_uuid(), 'Romanian', 'ro', true, true),
        (gen_random_uuid(), 'Greek', 'el', true, true),
        (gen_random_uuid(), 'Slovak', 'sk', true, true),
        (gen_random_uuid(), 'Japanese', 'ja', true, true),
        (gen_random_uuid(), 'Chinese', 'zh', true, true),
        (gen_random_uuid(), 'Indonesian', 'id', true, true),
        (gen_random_uuid(), 'Turkish', 'tr', true, true)"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM languages WHERE api_name NOT IN ('en', 'ru', 'fr', 'de', 'it')")
    op.drop_column('languages', 'target')
    op.drop_column('languages', 'source')
    # ### end Alembic commands ###
