"""create_feedbacks

Revision ID: bf1c8126abb5
Revises: af83582d0374
Create Date: 2023-12-13 08:02:24.152405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
from core.status import FeedbackEnum

# revision identifiers, used by Alembic.
revision = 'bf1c8126abb5'
down_revision = 'af83582d0374'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('feedbacks',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('localization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(FeedbackEnum, impl=sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['localization_id'], ['localizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'localization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    # ### end Alembic commands ###