"""add_airtable_field

Revision ID: d5a73f640d17
Revises: 4c1dae2170fc
Create Date: 2024-02-02 13:29:03.739388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a73f640d17'
down_revision = '4c1dae2170fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_been_invited_to_castdev', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_been_invited_to_castdev')
    # ### end Alembic commands ###

